#ifndef BOARD_CONFIG_H
#define BOARD_CONFIG_H

#include "n32g4fr.h"
#include "n32g4fr_adc.h"
#include "n32g4fr_gpio.h"

#include <stdint.h>

/* CJ40076 new main board, N32G4FRHEQ7 QFN40 schematic mapping. */
#define BOARD_BAT_ADC_PORT          GPIOA
#define BOARD_BAT_ADC_PIN           GPIO_PIN_0
#define BOARD_BAT_ADC_CHANNEL       ADC_CH_1

/* 主电源使能 PB12，开机拉高自锁系统供电 */
#define BOARD_PWR_HOLD_PORT         GPIOB
#define BOARD_PWR_HOLD_PIN          GPIO_PIN_12
#define BOARD_PWR_HOLD_ACTIVE_HIGH  1U

/* 显示板电源使能 PB4，开机拉高 */
#define BOARD_PWR_DISPLAY_PORT      GPIOB
#define BOARD_PWR_DISPLAY_PIN       GPIO_PIN_4
#define BOARD_PWR_DISPLAY_ACTIVE_HIGH 1U

/* 激光测距电源使能 PB3 */
#define BOARD_PWR_RANGE_PORT        GPIOB
#define BOARD_PWR_RANGE_PIN         GPIO_PIN_3
#define BOARD_PWR_RANGE_ACTIVE_HIGH 1U

/* 电子罗盘电源使能 PA8 */
#define BOARD_PWR_IMU_PORT          GPIOA
#define BOARD_PWR_IMU_PIN           GPIO_PIN_8
#define BOARD_PWR_IMU_ACTIVE_HIGH   1U

/* GNSS 电源使能 PA15 */
#define BOARD_PWR_GNSS_PORT         GPIOA
#define BOARD_PWR_GNSS_PIN          GPIO_PIN_15
#define BOARD_PWR_GNSS_ACTIVE_HIGH  1U

/* 电源键 PA5 */
#define BOARD_KEY_POWER_PORT        GPIOA
#define BOARD_KEY_POWER_PIN         GPIO_PIN_5
#define BOARD_KEY_POWER_ACTIVE_HIGH 0U

/* 模式键 PA4 */
#define BOARD_KEY_MODE_PORT         GPIOA
#define BOARD_KEY_MODE_PIN          GPIO_PIN_4
#define BOARD_KEY_MODE_ACTIVE_HIGH  0U

/* 电子罗盘 USART2 PA2/PA3，无重映射(RMP00) */
#define BOARD_USART2_TX_PORT        GPIOA
#define BOARD_USART2_TX_PIN         GPIO_PIN_2
#define BOARD_USART2_RX_PORT        GPIOA
#define BOARD_USART2_RX_PIN         GPIO_PIN_3
#define BOARD_USART2_REMAP          0U

/* GNSS USART1 PA9/PA10，无重映射 */
#define BOARD_GNSS_TX_PORT          GPIOA
#define BOARD_GNSS_TX_PIN           GPIO_PIN_9
#define BOARD_GNSS_RX_PORT          GPIOA
#define BOARD_GNSS_RX_PIN           GPIO_PIN_10
#define BOARD_GNSS_REMAP            0U

/* 显示板通讯 UART5 PB13/PB14，UART5_RMP[1:0]=01 */
#define BOARD_DISPLAY_TX_PORT       GPIOB
#define BOARD_DISPLAY_TX_PIN        GPIO_PIN_13
#define BOARD_DISPLAY_RX_PORT       GPIOB
#define BOARD_DISPLAY_RX_PIN        GPIO_PIN_14
#define BOARD_DISPLAY_REMAP         GPIO_RMP1_UART5

/* 激光测距 UART6 PB0/PB1，UART6_RMP[1:0]=11 */
#define BOARD_RANGE_TX_PORT         GPIOB
#define BOARD_RANGE_TX_PIN          GPIO_PIN_0
#define BOARD_RANGE_RX_PORT         GPIOB
#define BOARD_RANGE_RX_PIN          GPIO_PIN_1
#define BOARD_RANGE_REMAP           GPIO_RMP3_UART6

#define APP_GNSS_UART_BAUD          115200U
#define APP_JY901B_UART_BAUD        9600U
#define APP_RANGE_UART_BAUD         115200U
#define APP_DISPLAY_UART_BAUD       115200U

#define APP_SERIAL_DISPLAY_ENABLE   1U

#define APP_BAT_ADC_REF_MV          3300U
#define APP_BAT_DIVIDER_NUM         3U
#define APP_BAT_DIVIDER_DEN         2U
#define APP_BAT_EMPTY_MV            2600U

#define APP_KEY_DEBOUNCE_MS         40U
#define APP_MODE_MULTI_CLICK_MS     600U
#define APP_POWER_LONG_PRESS_MS     3000U
#define APP_AUTO_POWER_OFF_ENABLE   0U
#define APP_AUTO_POWER_OFF_MS       300000U

/* Temporary endurance-test mode: five multifunction measurements per minute. */
#ifndef APP_WORK_TIME_TEST_MODE_ENABLE
#define APP_WORK_TIME_TEST_MODE_ENABLE 1U
#endif
#define APP_WORK_TIME_TEST_INTERVAL_MS 12000U

#define APP_RANGE_COMMAND_GAP_MS    50U
#define APP_RANGE_COMMAND_ACK_TIMEOUT_MS 300U

#define APP_RANGE_SELFTEST_TIMEOUT_MS 2000U
#define APP_RANGE_SELFTEST_RETRY_MS   500U
#define APP_IMU_SELFTEST_TIMEOUT_MS   2000U
#define APP_GNSS_SELFTEST_TIMEOUT_MS  5000U
#define APP_RANGE_SINGLE_TIMEOUT_MS   3000U
#define APP_RANGE_CONTINUOUS_SAMPLES  10U
#define APP_RANGE_CONTINUOUS_TIMEOUT_MS 12000U
#define APP_MULTI_MEASURE_TIMEOUT_MS  5000U
#define APP_RANGE_SINGLE_GAP_TIMEOUT_MS 40U
#define APP_RANGE_CONTINUOUS_GAP_TIMEOUT_MS 200U

#endif /* BOARD_CONFIG_H */
